// SPDX-License-Identifier: Apache-2.0
import org.hiero.gradle.environment.EnvAccess
import org.hiero.gradle.problems.ProblemReporter

plugins {
    id("java")
    id("org.gradlex.reproducible-builds")
}

@Suppress("UnstableApiUsage") val rootDir = project.isolated.rootProject.projectDirectory
val versions = EnvAccess.toolchainVersions(rootDir, providers, objects)

val currentJavaVersion = providers.systemProperty("java.version").get()
val fullJavaVersion =
    versions
        .getting("jdk")
        .orElse(
            provider {
                objects
                    .newInstance<ProblemReporter>()
                    .warn(
                        "Java Version not Pinned",
                        "No 'jdk' version pinned (using: $currentJavaVersion)",
                        "gradle/toolchain-versions.properties",
                        "Add jdk=$currentJavaVersion to gradle/toolchain-versions.properties",
                    )
                currentJavaVersion
            }
        )
        .get()
val majorJavaVersion = JavaVersion.toVersion(fullJavaVersion)

if (currentJavaVersion != fullJavaVersion) {
    objects
        .newInstance<ProblemReporter>()
        .warn(
            "Wrong Java Version",
            "Gradle runs with Java $currentJavaVersion. This project works best running with Java $fullJavaVersion",
            "gradle/toolchain-versions.properties",
            "Point at Java $fullJavaVersion installation: " +
                "JAVA_HOME and/or PATH (command line), " +
                "'Gradle JVM' in 'Gradle Settings' (IntelliJ)",
        )
}

java {
    sourceCompatibility = majorJavaVersion
    targetCompatibility = majorJavaVersion
}

tasks.withType<JavaCompile>().configureEach {
    // Track the full Java version as input (e.g. 17.0.3 vs. 17.0.9).
    // By default, Gradle only tracks the major version as defined in the toolchain (e.g. 17).
    // Since the full version is encoded in 'module-info.class' files, it should be tracked as
    // it otherwise leads to wrong build cache hits.
    inputs.property("fullJavaVersion", currentJavaVersion)

    options.javaModuleVersion = provider { project.version as String }

    options.isFork = true // run compiler in separate JVM process (independent of toolchain setup)

    doLast {
        // Make sure consistent line ending are used in files generated by annotation processors by
        // rewriting generated files.
        // To fix this problem at the root, one of these issues needs to be addressed upstream:
        // - https://github.com/google/auto/issues/1656
        // - https://github.com/gradle/gradle/issues/27385
        if (System.lineSeparator() != "\n") {
            destinationDirectory
                .get()
                .asFileTree
                .filter { it.extension != "class" }
                .forEach {
                    val content = it.readText()
                    val normalizedContent = content.replace(System.lineSeparator(), "\n")
                    if (content != normalizedContent) {
                        it.writeText(normalizedContent)
                    }
                }
        }
    }
}

tasks.jar {
    manifest {
        attributes["Implementation-Title"] = project.name
        attributes["Implementation-Version"] = project.version
    }
}

sourceSets.all {
    // 'assemble' compiles all sources, including all test sources
    tasks.assemble { dependsOn(tasks.named(classesTaskName)) }
}
