# SPDX-License-Identifier: Apache-2.0
name: "ZXC: Compile"
on:
  workflow_call:
    secrets:
      gradle-cache-username:
        description: "The username used to authenticate with the Gradle Build Cache Node."
        required: true
      gradle-cache-password:
        description: "The password used to authenticate with the Gradle Build Cache Node."
        required: true

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8
  GRADLE_CACHE_USERNAME: ${{ secrets.gradle-cache-username }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.gradle-cache-password }}

jobs:
  compile:
    name: Compile and Test
    runs-on: hl-gc-gradle-lin
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: temurin
          java-version: 17.0.16

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: false
          build-scan-terms-of-use-url: https://gradle.com/terms-of-service
          build-scan-terms-of-use-agree: yes

      - name: Compile Code
        run: ./gradlew assemble

      - name: Code Quality Checks and Tests
        run: ./gradlew check

      - name: Publish JUnit Test Report
        uses: step-security/publish-unit-test-result-action@681100d67b09305624c089873f12c545ee7cbc24 # v2.23.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          check_name: JUnit Test Report
          time_unit: seconds
          junit_files: "build/test-results/**/*.xml"
